/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/basic/data/future': RouteRecordInfo<'/basic/data/future', '/basic/data/future', Record<never, never>, Record<never, never>>,
    '/basic/data/option': RouteRecordInfo<'/basic/data/option', '/basic/data/option', Record<never, never>, Record<never, never>>,
    '/basic/data/stock': RouteRecordInfo<'/basic/data/stock', '/basic/data/stock', Record<never, never>, Record<never, never>>,
    '/event/shioaji': RouteRecordInfo<'/event/shioaji', '/event/shioaji', Record<never, never>, Record<never, never>>,
    '/historical/kbar': RouteRecordInfo<'/historical/kbar', '/historical/kbar', Record<never, never>, Record<never, never>>,
    '/historical/ticks': RouteRecordInfo<'/historical/ticks', '/historical/ticks', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/realtime/future': RouteRecordInfo<'/realtime/future', '/realtime/future', Record<never, never>, Record<never, never>>,
    '/realtime/stock': RouteRecordInfo<'/realtime/stock', '/realtime/stock', Record<never, never>, Record<never, never>>,
    '/system/account': RouteRecordInfo<'/system/account', '/system/account', Record<never, never>, Record<never, never>>,
    '/system/backup': RouteRecordInfo<'/system/backup', '/system/backup', Record<never, never>, Record<never, never>>,
    '/system/quota': RouteRecordInfo<'/system/quota', '/system/quota', Record<never, never>, Record<never, never>>,
    '/system/robot': RouteRecordInfo<'/system/robot', '/system/robot', Record<never, never>, Record<never, never>>,
    '/trade/order': RouteRecordInfo<'/trade/order', '/trade/order', Record<never, never>, Record<never, never>>,
    '/trade/position': RouteRecordInfo<'/trade/position', '/trade/position', Record<never, never>, Record<never, never>>,
    '/trade/profit': RouteRecordInfo<'/trade/profit', '/trade/profit', Record<never, never>, Record<never, never>>,
    '/trade/records': RouteRecordInfo<'/trade/records', '/trade/records', Record<never, never>, Record<never, never>>,
  }
}
